// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hqwjqfsvkqqqqpefvniv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imhxd2pxZnN2a3FxcXFwZWZ2bml2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk0MzA3ODUsImV4cCI6MjA1NTAwNjc4NX0.n8U8dE6opjmUYB2Zd-1aSgERO0JZWVNhHrtCDiaUnvA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);